using CodePulse.API.Data;
using CodePulse.API.Models.Domain;
using CodePulse.API.Models.DTO;
using CodePulse.API.Repositories.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CodePulse.API.Controllers
{
    //https://localhost:xxxx/api/categories
    [Route("api/[controller]")]
    [ApiController]
    public class CategoriesController : ControllerBase
    {
        private readonly ICategoryRepository categoryRepository;

        public CategoriesController(ICategoryRepository categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }

        [HttpPost]
        public async Task<IActionResult> CreateCategory([FromBody] CreateCategoryRequestDto requestDto)
        {
            // Map the incoming request DTO to the domain model.
            // The domain model represents how data is stored in the database.
            var category = new Category
            {
                Name = requestDto.Name,
                UrlHandle = requestDto.UrlHandle
            };

            // Use the repository to save the new category to the database.
            await categoryRepository.CreateCategoryAsync(category);

            // Map the saved domain model back to a response DTO.
            // This ensures we only return the data we want to expose to the client.
            var response = new CategoryDto
            {
                Id = category.Id,          // Generated by the database after SaveChangesAsync
                Name = category.Name,
                UrlHandle = category.UrlHandle
            };

            // Return HTTP 200 OK with the response DTO.
            return Ok(response);
        }

        //Get: https://localhost:7213/api/categories
        [HttpGet]
        public async Task<IActionResult> GetAllCategories()
        {
            var categories = await categoryRepository.GetAllCategoriesAsync();
            // Map domain models to DTOs
            //The Select() LINQ method loops through each category and transforms it. we don't need an explicit foreach loop.
            var response = categories.Select(category => new CategoryDto
            {
                Id = category.Id,
                Name = category.Name,
                UrlHandle = category.UrlHandle
            }).ToList();

            return Ok(response);
        }

        //Get : https://localhost:7213/api/categories/{id}
        [HttpGet("{id:Guid}")]
        public async Task<IActionResult> GetCategoryById([FromRoute] Guid id)
        {
            var category = await categoryRepository.GetCategoryByIdAsync(id);
            if (category == null)
            {
                return NotFound(); // Return 404 if the category is not found
            }
            var response = new CategoryDto
            {
                Id = category.Id,
                Name = category.Name,
                UrlHandle = category.UrlHandle
            };
            return Ok(response);
        }

        //PUT : https://localhost:7213/api/categories/{id}
        [HttpPut("{id:Guid}")]
        public async Task<IActionResult> UpdateCategory([FromRoute] Guid id, [FromBody] UpdateCategoryRequestDto requestDto)
        {
            //convert DTO to domain model
            var category = new Category
            {
                Id = id,
                Name = requestDto.Name,
                UrlHandle = requestDto.UrlHandle
            };

            category = await categoryRepository.UpdateCategory(category);

            if (category == null)
            {
                return NotFound(); // Return 404 if the category to update is not found
            }

            var response = new CategoryDto
            {
                Id = category.Id,
                Name = category.Name,
                UrlHandle = category.UrlHandle
            };

            return Ok(response);
        }

        //DELETE : https://localhost:7213/api/categories/{id}
        [HttpDelete("{id:Guid}")]
        public async Task<IActionResult> DeleteCategory([FromRoute] Guid id)
        {
            var category = await categoryRepository.GetCategoryByIdAsync(id);
            if (category == null)
            {
                return NotFound(); // Return 404 if the category to delete is not found
            }
            await categoryRepository.DeleteCategoryAsync(id);
            return NoContent(); // Return 204 No Content to indicate successful deletion
        }
    }
}
