namespace CodePulse.API.Models.DTO
{
    public class CreateCategoryRequestDto
    {
        // No Id property because it will be generated by the database
        public string Name { get; set; }
        public string UrlHandle { get; set; }
    }
}
